version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: coin_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: cointracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coin-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cointracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: coin_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - coin-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: coin_redis
    ports:
      - "6379:6379"
    networks:
      - coin-net

  mongo:
    image: mongo:latest
    container_name: coin_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - coin-net

  mongo-express:
    image: mongo-express
    container_name: coin_mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin_password@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - coin-net
    depends_on:
      - mongo

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: coin_redis_ui
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - coin-net
    depends_on:
      - redis

  worker-crypto:
    image: coin-worker-crypto
    container_name: coin_worker_crypto
    build:
      context: .
      dockerfile: src/Worker.Crypto/Dockerfile
    env_file:
      - common.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - coin-net

  worker-price:
    image: coin-worker-price
    container_name: coin_worker_price
    build:
      context: .
      dockerfile: src/Worker.PriceProcessor/Dockerfile
    env_file:
      - common.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - coin-net

  # api-analytics:
  #   image: coin-api-analytics
  #   container_name: coin_api_analytics
  #   build:
  #     context: .
  #     dockerfile: src/Api.Analytics/Dockerfile
  #   env_file:
  #     - common.env
  #   environment:
  #     - ASPNETCORE_URLS=http://+:8080
  #   ports:
  #     - "5000:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   networks:
  #     - coin-net

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: coin_migrator
    volumes:
      - ./src:/src
    command: >
      bash -c "
      echo 'Limpando artefatos do Windows...' &&
      find /src -type d -name bin -exec rm -rf {} + &&
      find /src -type d -name obj -exec rm -rf {} + &&
      
      echo 'Instalando EF Tool...' &&
      dotnet tool install --global dotnet-ef &&
      export PATH=\"$$PATH:/root/.dotnet/tools\" &&
      
      echo 'Restaurando dependencias (Linux)...' &&
      dotnet restore /src/Worker.PriceProcessor/Worker.PriceProcessor.csproj &&
      
      echo 'Rodando Migration...' &&
      dotnet ef database update --project /src/Core.Lib --startup-project /src/Worker.PriceProcessor --verbose
      "
    env_file:
      - common.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coin-net

volumes:
  postgres_data:
  mongo_data:

networks:
  coin-net:
    driver: bridge