version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: coin_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: cointracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coin-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: coin_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - coin-net

  redis:
    image: redis:alpine
    container_name: coin_redis
    ports:
      - "6379:6379"
    networks:
      - coin-net

  mongo:
    image: mongo:latest
    container_name: coin_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - coin-net

  mongo-express:
    image: mongo-express
    container_name: coin_mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin_password@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - coin-net
    depends_on:
      - mongo

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: coin_redis_ui
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - coin-net
    depends_on:
      - redis

  worker-crypto:
    image: coin-worker-crypto
    container_name: coin_worker_crypto
    build:
      context: .
      dockerfile: src/Worker.Crypto/Dockerfile
    env_file:
      - common.env
    depends_on:
      - rabbitmq
    networks:
      - coin-net

  worker-price:
    image: coin-worker-price
    container_name: coin_worker_price
    build:
      context: .
      dockerfile: src/Worker.PriceProcessor/Dockerfile
    env_file:
      - common.env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - coin-net

volumes:
  postgres_data:
  mongo_data:

networks:
  coin-net:
    driver: bridge